#!/bin/bash

# Revisamos si ya corrio el archivo de configuracion
#echo FMRILAB_CONFIGFILE_RAN  vale $FMRILAB_CONFIGFILE_RAN 
if [ ! -z $FMRILAB_CONFIGFILE_RAN ]
then
  echo ""
  #return 1
fi

# Don clusterio LOGO
logo=/home/inb/soporte/admin_tools/fmrilab_logo.txt
cat $logo


# modules config
source /etc/profile.d/modules.sh  # define el comando module
export MODULEPATH=/home/inb/soporte/admin_tools/modulesfiles # carga el path de los modulos de don clusterio
module load inb_tools # cargamos las inb_tools por default a todo usuario del cluster

# SGE config
if [ -d /opt/sge ]
then
  export SGE_ROOT=/opt/sge
  fmrilab_sge_file=${SGE_ROOT}/fmrilab/common/settings.sh
  if [ -f $fmrilab_sge_file ]
  then
    source ${SGE_ROOT}/fmrilab/common/settings.sh
  else
    echo " [AGUAS] gridengine mal configurado, no existe $fmrilab_sge_file"
    unset SGE_ROOT
  fi
else
    echo " [AGUAS] gridengine mal configurado, no existe /opt/sge"
    unset SGE_ROOT
fi


# ALIAS/funciones temporales para retro-compatibilidad.
# Eliminar cuando los usuarios se acostumbren a los modulos
MENSAJE_ALIAS="Este comando pronto será desactivado. Se cargó el software pero empieza a usar módulos para eso. Mas info en https://github.com/c13inb/c13inb.github.io/wiki/Cl%C3%BAster:-M%C3%B3dulos"
fsl6 () {
  echo $MENSAJE_ALIAS
  module load fsl
}

mrtrix3 () {
  echo $MENSAJE_ALIAS
  module load mrtrix
}

freesurfer7 () {
  echo $MENSAJE_ALIAS
  module load freesurfer
}


# ALIAS
alias scpresume="rsync -av --partial --progress --rsh=ssh"


# Una bandera para avisar que este archivo ya corrio
# La intencion es que /etc/profile lo corre system-wide, y luego cada usuario,
# pero para que correrlo dos veces?
export FMRILAB_CONFIGFILE_RAN=1

echo "Hola `whoami`. Bienvenido a `uname -n`."
echolor green "---------------------------------------------------------------"
echolor green " Usa módulos para ajustar tu ambiente:"
echolor green "     'module avail' - Muestra los módulos disponibles."
echolor green "     'module load <module>' - Carga el módulo para esta sesión."
echolor green " Más información en https://researchcomputing.princeton.edu/support/knowledge-base/modules "
echolor green "---------------------------------------------------------------"
echolor green " Python: Instala tu propia Anaconda o miniconda. Instrucciones:"
echolor green "         https://github.com/c13inb/c13inb.github.io/wiki/Anaconda"
echolor green "---------------------------------------------------------------"
echo "Visita la wiki:"
wikiURL=https://github.com/c13inb/c13inb.github.io/wiki
echolor cyan "$wikiURL"
echo ""
echolor bold "  RESPALDOS: SOLO PCS DEL C13 SE RESPALDAN AUTOMATICAMENTE"
echolor bold "             Todos los demás laboratorios deben tener su propia estrategia de respaldo."
echo ""
