#!/bin/bash


# Configuramos fsl version 5
unset FSLDIR

# removemos cualquier otra version de fsl en el PATH
PATH=$(IFS=':';p=($PATH);unset IFS;p=(${p[@]%%*fsl*});IFS=':';echo "${p[*]}";unset IFS)
export PATH

export FSLDIR=/home/inb/soporte/lanirem_software/fsl_6.0.7.1
export PATH=${FSLDIR}/bin:${PATH}
. ${FSLDIR}/etc/fslconf/fsl.sh
export FSLPARALLEL=1
#export LD_LIBRARY_PATH=${FSLDIR}/lib:${LD_LIBRARY_PATH}
# force fslview to use this version
alias fslview=${FSLDIR}/bin/fslview_deprecated

#echo ""
#echo "Ha sido configurado fsl version 6"
#echo "  FSLDIR = ${FSLDIR}"
#echo "  (para regresar a la version 4 utiliza el comando fsl4)"
#echo ""

