#!/bin/bash


# Configuramos fsl version 5
unset FSLDIR

# removemos cualquier otra version de fsl en el PATH
PATH=$(IFS=':';p=($PATH);unset IFS;p=(${p[@]%%*fsl*});IFS=':';echo "${p[*]}";unset IFS)
export PATH

export FSLDIR=/home/inb/lconcha/fmrilab_software/fsl_5.0.6
#export FSLDIR=/home/inb/lconcha/fmrilab_software/fsl_5.0.9
export PATH=${FSLDIR}/bin:${PATH}
. ${FSLDIR}/etc/fslconf/fsl.sh
export FSLPARALLEL=1
export LD_LIBRARY_PATH=${FSLDIR}/lib:${LD_LIBRARY_PATH}
# force fslview to use this version
alias fslview=${FSLDIR}/bin/fslview

#echo ""
#echo "Ha sido configurado fsl version 5"
#echo "  FSLDIR = ${FSLDIR}"
#echo "  (para regresar a la version 4 utiliza el comando fsl4)"
#echo ""

