#!/bin/bash

# Configuramos fsl version 4
unset FSLDIR

# removemos cualquier otra version de fsl en el PATH
PATH=$(IFS=':';p=($PATH);unset IFS;p=(${p[@]%%*fsl*});IFS=':';echo "${p[*]}";unset IFS)
export PATH

export FSLDIR=/home/inb/lconcha/fmrilab_software/fsl_4.1.9
export PATH=${FSLDIR}/bin:${PATH}
. ${FSLDIR}/etc/fslconf/fsl.sh
export FSLPARALLEL=1
export LD_LIBRARY_PATH=${FSLDIR}/lib:${LD_LIBRARY_PATH}
# force fslview to use version 4
#alias fslview=/usr/bin/fslview

echo ""
echo "Ha sido configurado fsl version 4.1.9"
echo "  FSLDIR = ${FSLDIR}"
echo "  (para regresar a la version 5 utiliza el comando fsl5)"
echo ""

